### ISSUE TITLE
'selector-naming-convention' default pattern too severe

### ISSUE THREAD

**Issue by axel3rd** [SonarCommunity/sonar-css#118]
Hi, 

The *css:selector-naming-convention* default pattern (``^[a-z][a-z\-]*$`` : #32) seems to be a little severe.

According :
* [this topic](http://stackoverflow.com/a/449000/1485989)
* The CSS usage/override of common frameworks/components like [bootstrap](http://getbootstrap.com/css/#grid-example-basic) / [jGrowl](https://github.com/stanlemon/jGrowl/blob/master/jquery.jgrowl.css) (for which we can consider CSS 'correct')

A default pattern more convenient could be :
``
^[a-z][a-zA-Z0-9\-]*$
``

SonarQube platform provides capacity to configure that ... but the defaults rules/patterns must be worldwide used.

Best regards.

**Comment by racodond** [comment]
Hi,

I'm ready to add `0-9` to the pattern.
But I'm against adding `A-Z`. Indeed, as HTML is case-insensitive (and usually written in lowercase then), I find it confusing and error-prone to be able to add CSS styles with uppercase letters. By the way, I would add this explanation to the rule description to explain the choice of the regular expression.

For the specific usages you mentioned, I would prefer you to configure the regular expression. 

@axel3rd @kalidasya What do you think?

**Comment by axel3rd** [comment]
@racodond : I understand the case of uppercase ; I hope that it will be understood by developers. OK for me.

**Comment by axel3rd** [comment]
@racodond : And WDYT about ``-`` (many usage in Boostrap) ?

**Comment by racodond** [comment]
> @racodond : And WDYT about - (many usage in Boostrap) ?

`-` is already allowed as the default regular expression is `^[a-z][a-z\-]*$`

**Comment by axel3rd** [comment]
@racodond : Oups, my apologies.

**Comment by racodond** [comment]
To be reviewed: https://github.com/SonarCommunity/sonar-css/pull/119
