### ISSUE TITLE
zero-units : false positive for "0s" (seconds)

### ISSUE THREAD

**Issue by sasidhar** [SonarCommunity/sonar-css#123]
Sonar-css is showing an issue for "0s" (seconds) to remove the units, which will fail at least in Mozilla Firefox.

Check examples in this URL : https://developer.mozilla.org/en-US/docs/Web/CSS/time

Here's a list of dimensions that are not lengths, and always require units:

Angles : deg, grad, rad, turn
Times : s, ms
Frequencies : Hz, kHz
Resolutions : dpi, dpcm, dppx

Using SonarQube 5.1.2 with Sonar-CSS

**Comment by racodond** [comment]
@sasidhar Good catch! I'm gonna fix it.

**Comment by racodond** [comment]
Fixed in https://github.com/SonarCommunity/sonar-css/commit/a29699ae4cd567c2c7e2fcf9a9af13f291a22859

**Comment by sasidhar** [comment]
@racodond Took a snapshot and checked on my project source. Now it is working fine.

Thanks for quick fix.

**Comment by racodond** [comment]
@sasidhar Thanks for the feedback.
