### ISSUE TITLE
Potential box model size issue with padding: 0

### ISSUE THREAD

**Issue by Eschon** [SonarCommunity/sonar-css#135]
I get a Potential box model size issue on a rule that specifies only a width with a fallback and a padding of 0.

Is that intentional? Since the padding is 0 nothing gets added to the actual width so I think there is no issue.

Screenshot of the rule and issue:
![screen shot 2015-09-18 at 13 21 38](https://cloud.githubusercontent.com/assets/11647830/9958242/3f2dd822-5e08-11e5-8b01-56355362db0a.png)

**Comment by racodond** [comment]
This rule can indeed be improved to not raise an issue when padding or border is set to 0. Issue added to the next version.
Thanks for your feedback @Eschon!

**Comment by racodond** [comment]
Fixed in https://github.com/SonarCommunity/sonar-css/commit/f878ca950265d36ca9f97100c941e24477e31f72
It should remove most of the false positives when padding or border is set to 0.
