### ISSUE TITLE
Link to downloads doesn't have most recent versions

### ISSUE THREAD

**Issue by rmcroft** [SonarCommunity/sonar-css#143]
When you got to the download link:
Download: http://downloads.sonarsource.com/plugins/org/codehaus/sonar-plugins/css/sonar-css-plugin/

It doesn't have the most recent versions.  Per I conversation I had with the Sonar Source people they recommend publishing them to the github releases.

http://docs.sonarqube.org/display/DEV/Your+Plugin+in+SonarQube+Update+Center

The link mentioned above isn't supported now that they moved to their own server,

**Comment by racodond** [comment]
Good catch. This is now fixed: https://github.com/SonarCommunity/sonar-css/blob/master/README.md. Thanks!
