### ISSUE TITLE
Invalid documentation for font-face-browser-compatibility rule

### ISSUE THREAD

**Issue by mkordas** [SonarCommunity/sonar-css#144]
In description I see:
![image](https://cloud.githubusercontent.com/assets/5467276/10175072/41f322c2-66ed-11e5-9138-76280d53948b.png)
The title says:
![image](https://cloud.githubusercontent.com/assets/5467276/10175084/508582c6-66ed-11e5-9ba1-68ed5d533b73.png)

**Comment by racodond** [comment]
Thanks for the feedback! Fixed in https://github.com/SonarCommunity/sonar-css/commit/4ca244cd65d739800917ecedc517e94d0c3bc6b2

**Comment by mkordas** [comment]
Thank you David for fast turnaround!
