### ISSUE TITLE
Properly compute technical debt for rules with non-constant/issue remediation function.

### ISSUE THREAD

**Issue by kalidasya** [SonarCommunity/sonar-css#50]
This must be done by passing the cost while creating an issue like at https://github.com/racodond/sonar-java/blob/master/java-squid/src/main/java/org/sonar/plugins/java/api/JavaFileScannerContext.java#L46.

**Comment by racodond** [comment]
Fixed in https://github.com/SonarCommunity/sonar-css/commit/9d69299ff5243a03bc02f6025f10dbbd557a3140
