### ISSUE TITLE
Add rule: Property values should be valid (CSS2 and CSS3 validation)

### ISSUE THREAD

**Issue by racodond** [SonarCommunity/sonar-css#57]
Implemented for some CSS properties (commits in PR https://github.com/SonarCommunity/sonar-css/pull/47)

**Comment by racodond** [comment]
@kalidasya: I think that there is now a very decent coverage of properties by validators, see http://htmlpreview.github.io/?https://github.com/SonarCommunity/sonar-css/blob/master/doc/validators.html. Would you be able to run this check on your CSS code base and provide some feedback? Thanks.

**Comment by kalidasya** [comment]
I do not work on any css project at the moment, but I will try to test with some!

**Comment by racodond** [comment]
OK. Thanks!
