### ISSUE TITLE
Fix Grammar: 0 solid parsed as 0s olid

### ISSUE THREAD

**Issue by racodond** [SonarCommunity/sonar-css#67]
```border-bottom: 0 solid;``` is parsed as Dimension(0s) Identifier(olid). It should be parsed as Number(0) Identifier(solid).

**Comment by kalidasya** [comment]
is it fixed in one of the commits?

**Comment by racodond** [comment]
The root cause of the issue is that the grammar currently allows whitespaces between the number and the unit for a dimension. No whitespaces are allowed by the CSS specifications: http://www.w3.org/TR/css3-values/#length-value

Fix at the same time the same kind of discrepancy with percentage: http://www.w3.org/TR/css3-values/#percentage-value

**Comment by racodond** [comment]
Fixed in https://github.com/SonarCommunity/sonar-css/pull/71
