### ISSUE TITLE
Define number of statements as number of rules (= AT_RULE + RULESET)

### ISSUE THREAD

**Issue by racodond** [SonarCommunity/sonar-css#83]
@kalidasya: What do you think?

Instead of:
 ```builder.withSquidAstVisitor(CounterVisitor.<LexerlessGrammar>builder()
      .setMetricDef(CssMetric.STATEMENTS)
      .subscribeTo(CssGrammar.AT_KEYWORD, CssGrammar.SELECTOR, CssGrammar.DECLARATION)
      .build());```

**Comment by kalidasya** [comment]
hm.. I feel statements lower level than an at-rule... so in your case this:
```
body {
    background-color: #d0e4fe;
}

h1, h3 {
    color: orange;
    text-align: center;
}

p {
    font-family: "Times New Roman";
    font-size: 20px;
}
```
has 3 statements, in the current 9? I think a declaration is a statement. the at-rule and ruleset is a higher level (thats why I mapped to functions what did not work out well). Maybe we should create a new metric for at rule and rulesets...

**Comment by racodond** [comment]
I meant function not statement. And my apologies, I had completely forgotten about the issue with the complexity/function. Let's close the ticket till we found a way to compute the complexity (I noticed that a ticket was open about it).
