### ISSUE TITLE
Handle UTF-8 BOM files properly

### ISSUE THREAD

**Issue by dbolkensteyn** [SonarCommunity/sonar-css#88]
Currently, even if `sonar.sourceEncoding=UTF-8` is set, the CSS parser fails on the first BOM characters of UTF-8 files:

```
15:04:39.299 ERROR - Unable to parse file: C:\Users\dinesh\Desktop\sonarsource\Stackoverflow-question-30482045\global.cs
s
15:04:39.299 ERROR - Parse error at line 1 column 2:

 1: ï»¿@import url('navigation.css');
     ^
 2:
 3: html, body, div, span, iframe, h1, h2, h3, h4, h5, h6, a, p, abbr, acronym, address, cite, code, dfn, em, font, img,
```

**Comment by dbolkensteyn** [comment]
See http://stackoverflow.com/questions/30482045/csssquidsensor-and-javascriptsquidsensor-both-fail-with-parse-errors-when-byte-o/

**Comment by kalidasya** [comment]
I have no idea what is causing it. @racodond ?

**Comment by racodond** [comment]
@kalidasya: I don't know if it is the best way to deal with it but it seems to be fixed in https://github.com/SonarCommunity/sonar-css/pull/94

**Comment by kalidasya** [comment]
if it fixed it fine by me!
